### ISSUE TITLE
Humidity cont be read properly

### ISSUE THREAD

**Issue by ghost** [catdog2/mpy_bme280_esp8266#10]
I imported the code to my ESP32 with miropython.
Every time I try to read the values with
`print(bme.values)`
I get "('20.32C', '968.83hPa', '0.00%')"
The temperature and pressure are correct, but the humidity is definitive not 0%

**Comment by catdog2** [comment]
Are you sure it's a BME280? You might have a BMP280 which does not support humidity.

**Comment by ghost** [comment]
I bought it as an BME280.
On the bag it says GY-BME/Pm 280

**Comment by ghost** [comment]
So long story short, the seller made a mistake and sold me a BMP280.
Thank you for helping to solve the problem.
