### ISSUE TITLE
fix "negative" temperature 

### ISSUE THREAD

**Issue by miroslavbucek** [catdog2/mpy_bme280_esp8266#4]
[https://dl.dropboxusercontent.com/u/574903/bordel/temperature-error.png](https://dl.dropboxusercontent.com/u/574903/bordel/temperature-error.png)

thanks!

**Comment by dragomirecky** [comment]
It should be fixed in my fork – d7e052b28281942996a8f0e1bbdbef87f87bbb8e.
Let me know if it works (I am not able to test it as I don't have the sensor with me). If yes, I will create a push request.

**Comment by catdog2** [comment]
Thx for the fix, I have included your commit.
