### ISSUE TITLE
OSError: [Errno 19] ENODEV

### ISSUE THREAD

**Issue by danbenhart** [catdog2/mpy_bme280_esp8266#5]
I'm using this driver as documented in the readme file, but I keep getting the following error:

```
bme = bme280.BME280(i2c=i2c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "micropython_BME280.py", line 74, in __init__
OSError: [Errno 19] ENODEV

```
I am also having some issues where the call to import the driver does not run the import statements in the driver; e.g. import bme280 does not run BME280_I2CADDR = 0x77. Regardless, then I run all of those imports and setup manually, I still get this error.

For reference:

- The board is an Adafruit Feather Huzzah
- Firmware version 1.9
    - I have not tried other firmware versions
- No other devices on the bus (but I confirmed that other devices work with this board and firmware config)
- There are no pull-up/down resistors on the pins
- i2c.scan() successfully returns [119]
    - As noted above, I changed the address to 0x77 in the driver since that's the default address per the datasheet and the i2c.scan() results.

Also, I ran through some of the steps manually. I set up the device and registers and ran the readfrom_mem() command. I was able to get the values from the register, so I know that the device works at least partially.

If any additional information is needed for troubleshooting, please let me know.

**Comment by danbenhart** [comment]
As a follow-up test, I've re-flashed the Huzzah board with the Arduino IDE and used the official Adafruit library. Using this configuration, I had no issues getting the values from the board.

Also, I flashed the board with micropython firmware version 1.8.6 and got a similar, but slightly different error:

`
import bme280
import machine
i2c = machine.I2C(scl=machine.Pin(5), sda=machine.Pin(4))
bme = bme280.BME280(i2c=i2c)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bme280.py", line 74, in __init__
OSError: I2C bus error
`

I hope this helps the troubleshooting process.

**Comment by danbenhart** [comment]
The issue has resolved itself. I'm not sure what was causing the problem, but the sensor is working correctly now.

**Comment by romax1407** [comment]
Solved !
You just need to pull your SDA line up to 3V3 over 5k resistor.

I checked and tested my circuit with the resistor on and off.
